export type ProductCategory = "Shalwar Kameez" | "Kurta" | "Dupatta" | "Trouser";
export type ProductColor = "Red" | "Green" | "Blue" | "White" | "Black" | "Pink";
export type ProductSize = "S" | "M" | "L" | "XL";

export interface Product {
  id: string;
  name: string;
  category: ProductCategory;
  price: number;
  description: string;
  images: string[];
  sizes: ProductSize[];
  colors: ProductColor[];
  rating: number;
  reviews: number;
  isFeatured?: boolean;
  isNew?: boolean;
}

export const products: Product[] = [
  {
    id: "cotton-shalwar-kameez",
    name: "Cotton Shalwar Kameez",
    category: "Shalwar Kameez",
    price: 1499,
    description: "Comfortable cotton stitched Shalwar Kameez, perfect for everyday wear.",
    images: [
      "/images/image.jpg",
      "/images/images%20(1).jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Blue"],
    rating: 4.6,
    reviews: 124,
    isFeatured: true,
  },
  {
    id: "lawn-shalwar-kameez",
    name: "Premium Lawn Shalwar Kameez",
    category: "Shalwar Kameez",
    price: 2499,
    description: "Elegant lawn fabric stitched Shalwar Kameez with beautiful embroidery.",
    images: [
      "/images/images.jfif",
      "/images/images%20(2).jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Green"],
    rating: 4.8,
    reviews: 88,
    isFeatured: true,
  },
  {
    id: "chiffon-dupatta",
    name: "Chiffon Dupatta",
    category: "Dupatta",
    price: 899,
    description: "Beautiful pure chiffon dupatta with delicate embellishments.",
    images: [
      "/images/images%20(1).jfif",
      "/images/images.jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Blue"],
    rating: 4.5,
    reviews: 209,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "organza-dupatta",
    name: "Organza Dupatta",
    category: "Dupatta",
    price: 1099,
    description: "Sheer organza dupatta with floral motifs and lightweight drape.",
    images: [
      "/images/images%20(5).jfif",
      "/images/images3.jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "White"],
    rating: 4.5,
    reviews: 88,
    isFeatured: true,
  },
  {
    id: "net-dupatta",
    name: "Net Dupatta with Sequins",
    category: "Dupatta",
    price: 1299,
    description: "Designer net dupatta with sequin border for festive occasions.",
    images: [
      "/images/images%20(6).jfif",
      "/images/images%20(5).jfif",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Red", "Blue"],
    rating: 4.7,
    reviews: 156,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "cashmere-dupatta",
    name: "Cashmere Blend Dupatta",
    category: "Dupatta",
    price: 1899,
    description: "Premium cashmere blend dupatta, soft and luxurious feel.",
    images: [
      "/images/images3.jfif",
      "/images/images.jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    rating: 4.9,
    reviews: 67,
    isFeatured: true,
  },
  {
    id: "silk-trouser",
    name: "Silk Trouser",
    category: "Trouser",
    price: 1299,
    description: "Premium silk-blend stitched trouser with elegant drape and comfort.",
    images: [
      "/images/tr2.jfif",
      "/images/tr3.jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Red"],
    rating: 4.7,
    reviews: 143,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "cigarette-trouser",
    name: "Cigarette Trouser",
    category: "Trouser",
    price: 999,
    description: "Slim-fit cigarette trouser with clean lines, ideal for office and casual wear.",
    images: [
      "/images/tr3.jfif",
      "/images/tr4.jfif",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Black", "White"],
    rating: 4.4,
    reviews: 71,
    isFeatured: true,
  },
  {
    id: "wide-leg-trouser",
    name: "Wide Leg Trouser",
    category: "Trouser",
    price: 1499,
    description: "Trendy wide-leg trouser with a flowing silhouette for a modern look.",
    images: [
      "/images/tr4.jfif",
      "/images/tr2.jfif",
    ],
    sizes: ["M", "L", "XL"],
    colors: ["Blue", "Green"],
    rating: 4.6,
    reviews: 58,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "embroidered-trouser",
    name: "Embroidered Hem Trouser",
    category: "Trouser",
    price: 1799,
    description: "Straight-cut trouser with delicate embroidered hem for festive styling.",
    images: [
      "/images/tr2.jfif",
      "/images/tr3.jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Pink"],
    rating: 4.8,
    reviews: 94,
    isFeatured: true,
  },
  {
    id: "daily-cotton-kurta",
    name: "Daily Wear Cotton Kurta",
    category: "Kurta",
    price: 1199,
    description: "Soft cotton stitched Kurta, ideal for daily wear with vibrant prints.",
    images: [
      "/images/kurta.jfif",
      "/images/kurta1.jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Green", "Blue"],
    rating: 4.5,
    reviews: 97,
    isFeatured: true,
  },
  {
    id: "printed-geometric-kurta",
    name: "Printed Geometric Kurta",
    category: "Kurta",
    price: 1399,
    description: "Modern geometric print Kurta with pocket detail, perfect for casual outings.",
    images: [
      "/images/kurta1.jfif",
      "/images/kurta2.jfif",
    ],
    sizes: ["S", "M", "L"],
    colors: ["Blue", "White"],
    rating: 4.4,
    reviews: 62,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "formal-striped-kurta",
    name: "Formal Striped Kurta",
    category: "Kurta",
    price: 1699,
    description: "Elegant striped Kurta for formal events and office wear.",
    images: [
      "/images/kurta2.jfif",
      "/images/kurta.jfif",
    ],
    sizes: ["M", "L", "XL"],
    colors: ["Black", "White"],
    rating: 4.6,
    reviews: 45,
    isFeatured: true,
  },
  {
    id: "embroidery-kurta",
    name: "Embroidery Work Kurta",
    category: "Kurta",
    price: 2199,
    description: "Fine embroidery work Kurta with matching tape, ideal for Eid and weddings.",
    images: [
      "/images/kurta.jfif",
      "/images/kurta1.jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    rating: 4.8,
    reviews: 112,
    isFeatured: true,
    isNew: true,
  },
  {
    id: "festive-embroidered-kameez",
    name: "Festive Embroidered Kameez",
    category: "Shalwar Kameez",
    price: 3499,
    description: "Beautifully embroidered stitched Shalwar Kameez for Eid and special occasions.",
    images: [
      "/images/images.jfif",
      "/images/images%20(1).jfif",
    ],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Green"],
    rating: 4.3,
    reviews: 76,
  },
];
